INSERT INTO dogs (number, name, owner, breed, gender, classOrSpec) VALUES 
(67548, 'Bagel', 'Juno', 'Beagle', 'Male', 'Class'),
(57849, 'Cookie', 'Rob', 'Borzoi', 'Male', 'Specialty'),
(43280, 'Otis', 'Mary','Greyhound', 'Male', 'Class'),
(43829, 'Sammy', 'Bob', 'Deerhound', 'Female', 'Class'),
(58490, 'Oreo', 'Jeff', 'Whippet', 'Female', 'Specialty'),
(63585, 'Ava', 'James', 'Husky', 'Female', 'Class'),
(41535, 'Missy', 'Juliette', 'Pomeranian', 'Female', 'Specialty'), 
(27108, 'Riley', 'William', 'Rottweiler', 'Female', 'Class'), 
(99524, 'Ringo', 'Michael', 'Boxer', 'Male', 'Class'),
(39641, 'Prince', 'Benjamin', 'Cane Corso', 'Male', 'Specialty'),
(98816, 'Mya', 'Sam', 'Labrador','Female', 'Specialty'),
(58769, 'Nala', 'Gregory', 'Samoyed', 'Female', 'Class'),
(54301, 'Piper', 'Amy', 'Labradoodle', 'Female', 'Specialty'),
(50351, 'Rufus', 'Mark', 'Saint Bernard', 'Male', 'Class'),
(73851, 'Nellie', 'Amberly', 'Maltipoo', 'Female', 'Class'),
(63785, 'Otto', 'Steven', 'Bulldog', 'Male', 'Specialty'),
(00284, 'Milo', 'Daniel', 'Foxhound', 'Male', 'Class'),
(11744, 'Lily', 'James', 'Chihuahua', 'Female', 'Class'),
(42887, 'Koko', 'Betty', 'Eurasier', 'Male', 'Class'),
(93489, 'Kane', 'Anthony', 'Rottweiler', 'Male', 'Specialty'),
(50683, 'Jax', 'Jack', 'Greyhound', 'Male', 'Class'),
(44972, 'Kali', 'Rachel', 'Maltese', 'Female', 'Class'),
(93226, 'Duke', 'Walter', 'Mastiff', 'Male', 'Specialty'),
(99668, 'Coco', 'Lauren', 'Schnauzer', 'Male', 'Specialty'), 
(52007, 'Chip', 'Jack', 'Mudi', 'Male', 'Specialty'),
(73567, 'Juno', 'Kyle', 'Labrador', 'Male', 'Specialty'),
(36071, 'Rex', 'Ann', 'Beagle', 'Male', 'Class'), 
(26785, 'Ranger', 'Sean', 'German Shepherd', 'Male', 'Class'),
(71449, 'Tank', 'Jordan', 'Cane Corso', 'Male', 'Specialty'),
(17557, 'Taz', 'Judy', 'Bullmastiff', 'Male', 'Specialty'),
(13709, 'Rudy', 'Wayne', 'Terrier', 'Female', 'Specialty'),
(10020, 'Ricky', 'Danielle', 'Horgi', 'Male', 'Specialty'),
(22683, 'Nola', 'Grace', 'Huskita', 'Female', 'Specialty'),
(91615, 'Reese', 'Alan', 'Golden Retriever', 'Male', 'Class'),
(72343, 'Molly', 'Beverly', 'Schnauzer', 'Female', 'Specialty'),
(49016, 'Peanut', 'Sophie', 'Labrador', 'Male', 'Class'),
(70865, 'Muffin', 'Vincent', 'Pug', 'Male', 'Class'),
(17458, 'Maximus', 'Natalie', 'Drever', 'Male', 'Specialty'),
(88888, 'Bear', 'Pierre', 'German Shepherd', 'Male', 'Specialty'); 

INSERT INTO breeds (name) VALUES
('Beagle'),
('DachShund'),
('Whippet'),
('Corgi'),
('Borzoi'),
('Golden Retriever'),
('Chihuahua'),
('Shiba Inu'),
('RottWeiler'),
('Poodle');
