CREATE TABLE dogs (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, number double, name VARCHAR(20), owner VARCHAR(40), breed VARCHAR(40), gender VARCHAR(10), classOrSpec VARCHAR(20));
CREATE TABLE breeds (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, name VARCHAR(20));

